import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/Menu";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
      <link href="https://api.fontshare.com/v2/css?f[]=general-sans@200,300,400,500,600,700&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`antialiased`}
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}
